### ISSUE TITLE
Most Tichondrius Nighthold Voice Files Missing

### ISSUE THREAD

**Issue by GaryOakRobotron** [bloerwald/LegionFiles#28]
Aside from the one sound clip (\sound\creature\tichondrius\vo_703_tichondrius_01_m.ogg), none of this boss's many emotes are in the sound files. I have searched for them with the most recent listfile, and I have attempted to find them in the \unknown\ folder by doing a batch extension rename of the ".xxx" files to ".ogg" and attempting to play them individually in VLC.

I estimate there's between a dozen to 15 voice clips for Tichondrius in the Nighthold raid, and only one of his kill lines is included.

**Comment by Marlamin** [comment]
Sounds like a job for @tomrus88!

**Comment by tomrus88** [comment]
How about Sound\Creature\Steve\ sound files? That's not it?

**Comment by GaryOakRobotron** [comment]
... Steve? STEVE?

That's exactly it. Never in a hundred years did I expect them to be filed under... Steve. Thanks very much for the help!
