### ISSUE TITLE
7.2 - 6 news ogg files

### ISSUE THREAD

**Issue by hoxton22** [bloerwald/LegionFiles#29]
sound/creature/meryl_felstorm/vo_72_meryl_felstorm_battleshout_01.ogg
sound/creature/meryl_felstorm/vo_72_meryl_felstorm_battleshout_02.ogg
sound/creature/meryl_felstorm/vo_72_meryl_felstorm_battleshout_03.ogg
sound/creature/shadowserpent/mon_shadow_serpent_chuff_01.ogg
sound/creature/shadowserpent/mon_shadow_serpent_chuff_02.ogg
sound/creature/shadowserpent/mon_shadow_serpent_chuff_03.ogg

I tried to find more files before posting theses, but... can't find more :/

**Comment by justMaku** [comment]
Thanks for your contribution.
