### ISSUE TITLE
Hype

### ISSUE THREAD

**Issue by tomrus88** [bloerwald/LegionFiles#39]
http://paste2.org/ptwczcys

**Comment by Marlamin** [comment]
Oh my lord

**Comment by justMaku** [comment]
![giphy-1](https://cloud.githubusercontent.com/assets/2745656/23852093/765f436a-07e6-11e7-8ebb-1e23f41931ab.gif)

**Comment by tomrus88** [comment]
http://rgho.st/7zlDCVpJf

**Comment by tomrus88** [comment]
SOUND\DOODAD\GO_7WD_WARDEN_JUDGEMENTPOOL01_Loop_01.ogg
SOUND\DOODAD\GO_7WD_WARDEN_JUDGEMENTPOOL01_Loop_02.ogg

**Comment by tomrus88** [comment]
http://rgho.st/7HM558xjH
