### ISSUE TITLE
7.3.0.24473 Additions

### ISSUE THREAD

**Issue by jimmsta** [bloerwald/LegionFiles#54]
[listfile.zip](https://github.com/bloerwald/LegionFiles/files/1111039/listfile.zip)

See attached.

**Comment by WainPetopia** [comment]
This listfile seems to be missing a lot of entries that are present in the current version. Were the new entries added to an older version of listfile?

**Comment by Marlamin** [comment]
I'll process it and open a pull request for a complete version. Gimme a few minutes.

**Comment by Marlamin** [comment]
That should do for the first wave of 7.3 stuff. I'll ask around for more complete listfiles.

**Comment by WainPetopia** [comment]
Thanks. I'd join in and add stuff but I'm having trouble opening 7.3 so far. Ladik's CASCView is giving errors :/

**Comment by Marlamin** [comment]
Install and download now have both keys in buildconfig as of 7.3 just like encoding does, I had to adapt my tools as well to support this. That should be it for changes on the CASC side.

**Comment by WainPetopia** [comment]
sweet, thanks! Is there a place I can get a precompiled CASCView that is updated? The one on Ladik's site is still from February.

**Comment by Marlamin** [comment]
Not sure anyone actually updated Ladik's casclib yet. You'll either have to do it yourself or wait till someone posts an update to it.

**Comment by WainPetopia** [comment]
Oh I misunderstood then, sorry. What program were you referring to then?

**Comment by Marlamin** [comment]
My own CASC implementation.

**Comment by WainPetopia** [comment]
Oh! I didn't know you had one. Can you please point me to it? :)

**Comment by Marlamin** [comment]
There's no manual and it's not at all useful for you probably, but it can
be found here https://github.com/Marlamin/BuildBackup

**Comment by WainPetopia** [comment]
Ah ok thank you :)
