### ISSUE TITLE
Some updates to creature skins

### ISSUE THREAD

**Issue by WainPetopia** [bloerwald/LegionFiles#60]
I don't have permission to create a pull request, I don't think, so here are the additions:

[listfileupdates.diff.txt](https://github.com/bloerwald/LegionFiles/files/1115905/listfileupdates.diff.txt)

**Comment by bloerwald** [comment]
There shouldn't be anything preventing from making a pull request. It should be open to everyone.

**Comment by Marlamin** [comment]
Basically, fork this repo then push your changes to your fork. When viewing your repo there should be a "New Pull Request" button which should allow you to open a new pull request on this repo with the changes you've made to yours.

**Comment by WainPetopia** [comment]
Thanks for the explanation. :) I got it to work
