### ISSUE TITLE
http://pastebin.com/eSfciWWV - Hoxton22

### ISSUE THREAD

**Issue by hoxton22** [bloerwald/LegionFiles#8]
http://pastebin.com/eSfciWWV
 
Note that i've added 
creature/titanfemale2/titanfemale2_golden.blp
creature/harpy2fel/harpy2_felred.blp

But there are one more texture for the titanfemale and one more for the harpy, but i didn't found the right name for them =(

**Comment by bloerwald** [comment]
that would be creature/harpy2fel/harpy2_felgray.blp for one
