### ISSUE TITLE
[7.3] finally some FEW things to commit

### ISSUE THREAD

**Issue by hoxton22** [bloerwald/LegionFiles#81]
(i was not inactive, just trying to find some filenames, difficult....)

sound/spells/spell_pr_revamp_shadow_mindblast_impact_06.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_cast_01.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_cast_02.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_cast_03.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_precast_01.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_precast_01.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_precast_02.ogg
sound/spells/spell_pr_revamp_shadow_void_Eruption_precast_02.ogg

**Comment by bloerwald** [comment]
You list the last two files twice which might be a copy & paste error ;)

**Comment by hoxton22** [comment]
Didn't noticed it, my bad :/

**Comment by bloerwald** [comment]
Duplicates don't make merging it any more work, I just thought you may have copied something wrong and now something you found is missing :)
