### ISSUE TITLE
Need more BLS bruteforce!

### ISSUE THREAD

**Issue by smitrovic** [bloerwald/LegionFiles#82]
Creature\BoneGuardFel\BoneGuard.blp
Creature\BoneGuardFel\T_VFX_Fire01_A64_BLANK4.blp
Creature\BoneGuardFel\T_VFX_Fire_Anim02_128_Desat.blp
Creature\BoneGuardFel\T_VFX_Flare05_32.blp
Creature\BoneGuardFel\T_VFX_Flare05_A64.blp
Creature\BoneGuardFel\T_VFX_Freeze_C.blp
Creature\BoneGuardFel\T_VFX_Ring_Smoke_B.blp
Creature\Ghoul2\northrendghoul2_Blue.blp
Creature\Ghoul2\northrendghoul2_Dark.blp
Creature\Ghoul2\northrendghoul2_Grey.blp
Creature\Ghoul2\northrendghoul2_Red.blp
Creature\NightmareTreeHeart\NightmareTreeHeart_zhCN.blp
Creature\OrcSkeleton\OrcSkeletonBlue1.blp
Creature\OrcSkeleton\OrcSkeletonblue2.blp
Creature\OrcSkeleton\OrcSkeletonBrown1.blp
Creature\OrcSkeleton\OrcSkeletonBrown2.blp
Creature\OrcSkeleton\OrcSkeletonGreen1.blp
Creature\OrcSkeleton\OrcSkeletongreen2.blp
Creature\OrcSkeleton\OrcSkeletonRed1.blp
Creature\OrcSkeleton\OrcSkeletonred2.blp
Creature\OrcSkeleton\OrcSkeletonWhite1.blp
Creature\OrcSkeleton\OrcSkeletonWhite2.blp
Shaders\Vertex\glvs_150\Particle_Diffuse_T1.bls
Shaders\Vertex\glvs_150\Particle_Diffuse_T2.bls
Shaders\Vertex\glvs_420\Particle_Diffuse_T1.bls
Shaders\Vertex\glvs_420\Particle_Diffuse_T2.bls
Shaders\Vertex\mtlvs_1_1\Particle_Diffuse_T1.bls
Shaders\Vertex\mtlvs_1_1\Particle_Diffuse_T2.bls
Shaders\Vertex\vs_2_0\Particle_Diffuse_T1.bls
Shaders\Vertex\vs_2_0\Particle_Diffuse_T2.bls
Shaders\Vertex\vs_3_0\Particle_Diffuse_T1.bls
Shaders\Vertex\vs_3_0\Particle_Diffuse_T2.bls
Shaders\Vertex\vs_4_0\Particle_Diffuse_T1.bls
Shaders\Vertex\vs_4_0\Particle_Diffuse_T2.bls
Shaders\Vertex\vs_5_0\Particle_Diffuse_T1.bls
Shaders\Vertex\vs_5_0\Particle_Diffuse_T2.bls
Shaders\Vertex\VS_5_H\Particle_Diffuse_T1.bls
Shaders\Vertex\VS_5_H\Particle_Diffuse_T2.bls
Spells\Arcane_Wisps_DeSat_inverse_V2.blp
Spells\Arcane_Wisps_Shadow_Pass.blp
Spells\Mask_Sphere_HardEdge_Black.blp
Spells\WeaponTrail_RogueAgility.blp

**Comment by bloerwald** [comment]
You seem to be diffing against a different file than the one in the repository. Those creature BLPs were already in.
