### ISSUE TITLE
Missing Records!

### ISSUE THREAD

**Issue by Uthil** [bloerwald/LegionFiles#89]
After update Troglodyte2 & Wendigo2 new models are missing.

**Comment by bloerwald** [comment]
Uh. You mean we had them but now they are gone?!

**Comment by bloerwald** [comment]
Sorry, but can't reproduce:

```
~/LegionFiles$ git rev-parse HEAD
f08a5009ebe78e359202ce4adcde4ea0fb0bbe12
~/LegionFiles$ git grep wendigo2 
listfile.txt:creature/wendigo2/armorreflect4.blp
listfile.txt:creature/wendigo2/wendigo2.m2
listfile.txt:creature/wendigo2/wendigo200.skin
listfile.txt:creature/wendigo2/wendigo201.skin
listfile.txt:creature/wendigo2/wendigo202.skin
listfile.txt:creature/wendigo2/wendigo2_arctic.blp
listfile.txt:creature/wendigo2/wendigo2_black.blp
listfile.txt:creature/wendigo2/wendigo2_blue.blp
listfile.txt:creature/wendigo2/wendigo2_brown.blp
listfile.txt:creature/wendigo2/wendigo2_darkblue.blp
listfile.txt:creature/wendigo2/wendigo2_darkbrown.blp
listfile.txt:creature/wendigo2/wendigo2_grey.blp
listfile.txt:creature/wendigo2/wendigo2_white.blp
~/LegionFiles$ git grep troglodyte2  
listfile.txt:creature/troglodyte2/smoothreflect_round.blp
listfile.txt:creature/troglodyte2/troglodyte2.m2
listfile.txt:creature/troglodyte2/troglodyte200.skin
listfile.txt:creature/troglodyte2/troglodyte20062-00.anim
listfile.txt:creature/troglodyte2/troglodyte201.skin
listfile.txt:creature/troglodyte2/troglodyte2_ash.blp
listfile.txt:creature/troglodyte2/troglodyte2_blue.blp
listfile.txt:creature/troglodyte2/troglodyte2_brown.blp
listfile.txt:creature/troglodyte2/troglodyte2_purple.blp
listfile.txt:creature/troglodyte2/troglodyte2_red.blp
listfile.txt:creature/troglodyte2/troglodyte2_white.blp
listfile.txt:creature/troglodyte2/troglodyte2_yellow.blp
```

Which entries are missing?

**Comment by Marlamin** [comment]
Maybe the models got removed? Just a guess, unsure.

**Comment by Qartar** [comment]
Sometimes the encryption keys change and viewers won't have the latest keys to extract all files. I'd be surprised if they've been actually removed.

**Comment by Marlamin** [comment]
Encryption keys don't change, they're either known or not. These models
don't seem encrypted amd were added in 7.3 so I'm not sure why they would
stop showing up.

**Comment by Uthil** [comment]
After downloading the list file, previous was from sept 3rd, when checking on the creature folders those 2 were missing.

**Comment by bloerwald** [comment]
Checking _how_? You can manually open the listfile in a text editor and will see: those files are there.

**Comment by Qartar** [comment]
@Marlamin how certain are you? I've had a handful of files that had been extracted earlier fail to extract in a later version until I updated CascLib with additional keys. I understood this to mean that the keys on these files had been changed.

**Comment by bloerwald** [comment]
And I checked again. It just is not technically possible. Given the date it puts us at four options:

* before c32822d
* after c32822d
* after bee907b
* after ae7f304 == f08a50

Comparing these to the current head (f08a50) and filtering for removals (and thus also renames due to how git works), we find that

```
$ git show c32822d c32822d bee907b ae7f304 f08a50 | grep '^-[^-]'
-updateplugin.dll
```

there was a removal, but it is for a dll, not the models you named. I added back that file, so now there are no removals anymore between Sep 3 and today.

@Qartar There might have been files that at some point changed their encryption key. In fact there have been files where the encryption was just removed, so a change seems plausible.

In no case was there an encryption key for the named files though.

Also, the files would _still show_, not vanish, in any CASC browser I am aware of. The only thing that _could_ change, assuming that they use an unknown key now, but as of 7.3 we don't have any known files with unknown keys, so _these_ files can't be affected by this. Again, it would only make extraction impossible.

**Comment by Qartar** [comment]
@bloerwald thank you for the clarification. Agreed that encoding seems extremely unlikely to be the problem here.

**Comment by Jeromnimo** [comment]
I confirm I can open these models using latest listfile from here, as well as latest casclib from ladislav in WoW Model Viewer, so issue is elsewhere...

![image](https://user-images.githubusercontent.com/964308/30563671-e0398b12-9cc2-11e7-913f-cc13f2d2f371.png)
![image](https://user-images.githubusercontent.com/964308/30563709-fcd79566-9cc2-11e7-8ba5-b7b70437df04.png)

**Comment by bloerwald** [comment]
Thanks Jerome. 

@Uthil If you have any additional information confirming that shit is missing, please reopen. Else, please contact whoever is maintaining your CASC implementation.

**Comment by Uthil** [comment]
True, I can confirm them too by editing the .txt directly. Seems that something with CascViewer. I use the one from TomRus.

**Comment by Qartar** [comment]
Do you mean https://github.com/tomrus88/CASCExplorer? That repo hasn't been updated in two years. https://github.com/WoW-Tools/CASCExplorer is the fork you should be using.

**Comment by Uthil** [comment]
Yes I had it from Tomruss repo. Thanks for the info, I'll get the new from wow-tools. Cheers!
