### ISSUE TITLE
New Db2(WDC1?) in new ptr build

### ISSUE THREAD

**Issue by hoxton22** [bloerwald/LegionFiles#91]
The header is WDC1, i've never seen it before.

The structure look like SceneScript.db2, with huge lua script text.

This is only one new line for the listfile, but i hope this will spare your time.

Edit : Actually, i think all DB2 have a new header now, WDC1.

Path :
DBFilesClient/SceneScriptText.db2

**Comment by Marlamin** [comment]
Yup. Keep an eye on wiki the next few days. Simca will probably document it when it's been figured out. Not related to SceneScript specifically at all.

**Comment by hoxton22** [comment]
Another new DB2 filepath 
DBFilesClient/SceneScriptGlobalText.db2

There are 9 more db2 in the new build

**Comment by Marlamin** [comment]
It's likely they have already been found. 

We're still working on the build. Check [here](https://bnet.marlam.in/files.php#search=&page=1) for latest file list.

**Comment by hoxton22** [comment]
allright'
